my-snowflake-db:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: lv44893.europe-west4.gcp

      # User/password auth
      user: AIRBYTE_USER
      password: password
      # Snowflake connection detail
      role: AIRBYTE_ROLE
      database: AIRBYTE_DATABASE
      warehouse: AIRBYTE_WAREHOUSE
      schema: SCHOOL
      threads: 5
      client_session_keep_alive: False

      # optional
      connect_retries: 0 # default 0
      connect_timeout: 10 # default: 10
      retry_on_database_errors: False # default: false
      retry_all: False  # default: false